### ISSUE TITLE
Request for Localization in tl - Tagalog or Filipino

### ISSUE THREAD

**Issue by ergiegonzaga** [developersdo/opensource#105]
Hi sir, 

I am Ergie P. Gonzaga would like to ask If can translate your documentation in Tagalog or Filipino.

I am a utopian.io contributor and this in one of the project I want to have a tagalog or Filipino Translation.

I'll be waiting for your response sir,
More Power and Godbless.

**Comment by rmariuzzo** [comment]
Hi @ergiegonzaga, thank you for your willingness. However, I feel this project doesn't need translations right now. I will close this issue and when the project requires it I will reopen it.
