### ISSUE TITLE
Use debug instead of chalk-printer

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#108]
1. Removed chalk-printer dependency.
 2. Install [debug](https://github.com/visionmedia/debug) as a dependency.
 3. Replace chalk-printer log calls with debug.
    - Create logic namespace using the directory path. For example: `src/server/services/scraper/repos.js` use `services:scraper:repos` (never include `src/xxx` or `index`.

**Comment by pnkapadia6** [comment]
Hey @rmariuzzo! Can I take this up?
