### ISSUE TITLE
Fix LGTM issues

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#109]
LGTM reporst the following 9 alerts: https://lgtm.com/projects/g/developersdo/opensource/alerts/?mode=list we need to fix them all.

**Comment by celinrayen** [comment]
Linted off the code as reported by LGTM. I have a question out of curiosity. I saw that almost all of the rect components set their state off from the `constructor`. Though the result would be same, I'm curious why staying away from `constructor`?
