### ISSUE TITLE
Add a GitHub banner to README file

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#112]
1. Create a banner at: https://rmariuzzo.github.io/github-banner/
   - Use Kira template.
   - Set the name to: "Dominican Open Source".
   - Set the description to “Discover the open source ecosystem related to the Dominican Republic!”.
 2. Download the banner as a SVG file and store them at `.github/banner.svg` (create the directory if it doesn't exist).
 3. Add it a the top of the README file using markdown: `![{name} - {description]({path})`. The name and description is the one specified in point 1, and the path is the SVG file path.

**Comment by akashsara** [comment]
I'll do this!

**Comment by akashsara** [comment]
Heya, just a reminder to close this issue before someone else tried to solve it.

**Comment by rmariuzzo** [comment]
Thank you @akashsara
