### ISSUE TITLE
Implement an automated deployment system

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/opensource#15]
I do not know the current deployment process of this project but it seems not to be automated that is why I suggest using some tool such as Travis-ci [travis-ci](https://travis-ci.org/) or [deployhq](https://www.deployhq.com/pricing) which offer unlimited deployments to open sources projects.

**Comment by rmariuzzo** [comment]
@DannyFeliz this is a good initiative! The current manual process is pretty simple:

 1. `git checkout master`
 2. `yarn build`
 3. `git push origin master`

Can you setup something?

**Comment by DSchau** [comment]
I can pull this down guys. One second!

**Comment by DannyFeliz** [comment]
Closes by #16
