### ISSUE TITLE
Se debe mejorar el responsive

### ISSUE THREAD

**Issue by diegomichell** [developersdo/opensource#2]
Al ver en pantalla de Iphone 6, y tantos otros dispositiovos el contenido se descuadra

<img width="360" alt="screen shot 2017-06-28 at 10 36 46 pm" src="https://user-images.githubusercontent.com/4793805/27669048-b5cdb336-5c52-11e7-80f5-779568b2dec3.png">

**Comment by rmariuzzo** [comment]
Cool @diegomichell! Tenemos que hacerlo responsive, te animas a hacer un PR? Estamos utilizando [materialize-css](materializecss.com).

**Comment by diegomichell** [comment]
@rmariuzzo  Excelente, lo veo tarde, de hecho cuando lo abri ya estaba trabajando en la solucion, ya hicieron los cambios, aunque todavia veo algunas cosas que mejorar, vere si lo combino con mis cambios.
