### ISSUE TITLE
Strange behavior with the pagination when you navigate between pages

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/opensource#34]
![Pagination Issue](https://gifyu.com/images/Oct-13-2017-18-21-47.gif)

**Comment by rmariuzzo** [comment]
That's really, really strange... probably is the logic behind the pagination: https://github.com/developersdo/opensource/blob/master/src/client/pages/home/components/popular-repos/index.js#L39-L43

**Comment by Hekotoru** [comment]
i Will try to check this after work.

**Comment by rmariuzzo** [comment]
@Hekotoru all your mate!

**Comment by rmariuzzo** [comment]
Closing because this was related on the old choo implementation.
