### ISSUE TITLE
Improve popular repositories positioning

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#40]
Currently we are determining popular repositories by their `stargazers`. That said, if two or more repositories has the same amount of `stargazers` then all of them will have the same position. For example:

<img width="1032" alt="dominican open source communities 2017-10-20 12-22-16" src="https://user-images.githubusercontent.com/439839/31831398-66b6074c-b591-11e7-9450-97da4b4879e6.png">

Those positioning can be confusing, therefore, we would like to use more data points to determine repositories popularity. The new order should be determined by:

 1. `stargazers` desc.
 2. `forks` desc.
 3. `watchers` desc.
 4. `name` asc.

Things to do:

 - [x] Implement the new ordering logic ([here](https://github.com/developersdo/opensource/blob/909fff0935a3d7a6c70a142119b7f9ae0e58ee2a/src/client/components/repositories/popular/Popular.js#L28)).
 - [ ] Change the positioning logic and assign each repo their unique position ([here](https://github.com/developersdo/opensource/blob/909fff0935a3d7a6c70a142119b7f9ae0e58ee2a/src/client/components/repositories/popular/Popular.js#L30-L39)).

**Comment by pthomas931** [comment]
Attempted solving this in PR  #41
