### ISSUE TITLE
El responsive se rompe en muchos elementos y el nombre de la persona, desaparece.

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#72]
![capture-2017-10-26 16 58 19](https://user-images.githubusercontent.com/1808624/32076837-4c71f264-ba6f-11e7-9e04-e48c1f84dd03.jpg)

**Comment by Eduardoveras** [comment]
@rmariuzzo maybe esto se puede agregar al issue #79

**Comment by Eduardoveras** [comment]
Cambiare el estilo de las cartas para que sea mas responsive friendly

**Comment by Eduardoveras** [comment]
https://github.com/developersdo/opensource/pull/93 fixed on this PR
