### ISSUE TITLE
Resos.json genera una masa cantidad de información

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#73]
La data en JSON pesa aprox. **2MB**, esto es una petición fuerte para los usuarios.

Lo mejor sería reducir el JSON a la cantidad que se mostrará al inicio (ejemplo 9), y ya luego ir cargando con un sistema de paginado dinámico, los demás datos.

https://developersdo.github.io/opensource/data/repos.json

**Comment by Eduardoveras** [comment]
Creo que esto ahora mismo no es posible siendo un github page, almenos que alguien este dispuesto a poner un servidor como backend permanente.
