### ISSUE TITLE
About - Problemas Responsive

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#74]
![capture-2017-10-26 17 08 04](https://user-images.githubusercontent.com/1808624/32077125-51ef334a-ba70-11e7-942c-ee8430ea8ec6.jpg)

**Comment by mudstart** [comment]
Buenas raylinanthony  puedes informar con que dispositivo visualizaste este error.

Gracias.

**Comment by raylinanthony** [comment]
Hola, desde un Galaxy S7, pero entiendo que desde cualquier device va a fallar.

**Comment by mudstart** [comment]
Este issue fue solucionado en el pull request que he sometido 
p
