### ISSUE TITLE
I'm getting a poor performace when I use PageSpeed Insights tool

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#85]
![3](https://user-images.githubusercontent.com/1808624/32135714-96968ca2-bbd1-11e7-9209-a051c2d81838.png)
![2](https://user-images.githubusercontent.com/1808624/32135715-96ac951a-bbd1-11e7-9d10-eb9ba4bcbb7c.png)

**Comment by rmariuzzo** [comment]
@raylinanthony can you create specific tasks to improve the page performance? That way we have more complete data on specific issues, and what tasks are needed to be done.

**Comment by raylinanthony** [comment]
Sure sir!, Let me check it up and I'm about to do a list task!

**Comment by rmariuzzo** [comment]
Awesome!
