### ISSUE TITLE
Show a sandwich menu on small device.

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#86]
Why reason the header menu is getting hide? This shouldn't be hide on mobile. You can put this menu into a such as sandwich menu?
![2](https://user-images.githubusercontent.com/1808624/32135762-58356338-bbd2-11e7-87e4-4d878b1f2666.gif)

**Comment by rmariuzzo** [comment]
The initial release didn't took in consideration mobile. Now, it is a good time to make it truly responsive.

**Comment by raylinanthony** [comment]
It'll a great approach!

**Comment by rmariuzzo** [comment]
I forgot that we have a similar reported issue that was submitted before this one. Closing in favor of the first: #79.
