### ISSUE TITLE
Leverage browser caching for the following cacheable resources:

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#87]
Set this links up with caching expiration.

https://avatars0.githubusercontent.com/u/1013337?v=4 (5 minutes)
https://avatars1.githubusercontent.com/u/10523232?v=4 (5 minutes)
https://avatars2.githubusercontent.com/u/20671846?v=4 (5 minutes)
https://avatars2.githubusercontent.com/u/2547751?v=4 (5 minutes)
https://avatars2.githubusercontent.com/u/773158?v=4 (5 minutes)
https://avatars3.githubusercontent.com/u/1163358?v=4 (5 minutes)
https://avatars3.githubusercontent.com/u/15680836?v=4 (5 minutes)
https://avatars3.githubusercontent.com/u/439839?v=4 (5 minutes)
https://avatars3.githubusercontent.com/u/4788817?v=4 (5 minutes)
https://developersdo.github.io/opensource/app.js?8f533965e18cc0b0159b (10 minutes)
https://developersdo.github.io/opensource/data/repos.json (10 minutes)
https://developersdo.github.io/opensource/data/users.json (10 minutes)
https://developersdo.github.io/…pensource/vendor.js?8f533965e18cc0b0159b (10 minutes)
https://www.google-analytics.com/analytics.js (2 hours)

**Comment by rmariuzzo** [comment]
Unfortunately, we can't do anything with theses links as we don't own a server, but we use GitHub pages. That said, our own data can't be specified to be cache AFAIK. And as of external links, we can't do too much.

@raylinanthony any suggestion?

**Comment by raylinanthony** [comment]
I understand... Well in that case, the better should be migrate all data to a server. Whether you (for any reason) couldn't doing that. It hasn't any problem. :D

**Comment by rmariuzzo** [comment]
For now, I'm sticking to GitHub Pages. It is a free solution for something we are doing for fun.

**Comment by raylinanthony** [comment]
Ok, not problem
