### ISSUE TITLE
Optimize Images

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/opensource#88]
**Properly formatting and compressing images can save many bytes of data.**

Compressing and resizing https://avatars3.githubusercontent.com/u/439839?v=4 could save 257.2KiB (98% reduction).
Compressing and resizing https://avatars2.githubusercontent.com/u/20671846?v=4 could save 52.9KiB (98% reduction).
Compressing and resizing https://avatars3.githubusercontent.com/u/4788817?v=4 could save 28.8KiB (97% reduction).
Compressing and resizing https://avatars3.githubusercontent.com/u/1163358?v=4 could save 27.9KiB (97% reduction).
Compressing and resizing https://avatars2.githubusercontent.com/u/773158?v=4 could save 22.6KiB (97% reduction).
Compressing and resizing https://avatars2.githubusercontent.com/u/2547751?v=4 could save 22.4KiB (97% reduction).
Compressing and resizing https://avatars0.githubusercontent.com/u/1013337?v=4 could save 22KiB (97% reduction).
Compressing and resizing https://avatars1.githubusercontent.com/u/10523232?v=4 could save 16.6KiB (96% reduction).
Compressing and resizing https://avatars3.githubusercontent.com/u/15680836?v=4 could save 5.2KiB (93% reduction).

**Comment by rmariuzzo** [comment]
Here we need to identify if GitHub avatars support resizing. Otherwise, improving this may require additional work.

**Comment by rmariuzzo** [comment]
Looks like we can use the query string `s` to do resizing:

```html
<img alt="@rmariuzzo" class="timeline-comment-avatar" height="44" src="https://avatars0.githubusercontent.com/u/439839?s=88&amp;v=4" width="44">
```

**Comment by raylinanthony** [comment]
Amazing!, I'm looking that you realized a good job, Thanks. That's the better solution for improving web performance. Congratulations!
