### ISSUE TITLE
Fix text color of languages in RepositoryCard compnent

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#97]
<img width="449" alt="popular repositories dominican open source 2017-11-09 23-17-26" src="https://user-images.githubusercontent.com/439839/32641421-45ba9c30-c57a-11e7-82ed-5abd734aca87.png">

**Comment by wilburhimself** [comment]
@rmariuzzo this is handled in #95. Check the screenshot there.

**Comment by rmariuzzo** [comment]
My bad @wilburhimself! I checked the changes of the PR, but didn't paid attention to the screenshots. Sorry!

**Comment by rmariuzzo** [comment]
This was fixed on #95.
